objects = 21a 21b 22a 22b 22cq 22cs 23 25
cc = gcc

$(info **********Assignment-2**********)


all: $(objects)

21a: 21a.c
	$(cc) -o 21a 21a.c

21b: 21b.c
	$(cc) -o 21b 21b.c

22a: 22a.c
	$(cc) -o 22a 22a.c

22b: 22b.c
	$(cc) -o 22b 22b.c

22cq: 22cq.c
	$(cc) -o 22cq 22cq.c

22cs: 22cs.c
	$(cc) -o 22cs 22cs.c

23: 23.c
	$(cc) -o 23 23.c

25: 25.c
	$(cc) -o 25 25.c



.PHONY : clean
clean :
	\rm -fr $(objects)

