objects = 33a 33b 34 
cc = gcc

all: $(objects)
	
$(info **********Assignment-3**********)

33a: 33a.c
	$(cc) -o 33a 33a.c

33b: 33b.c
	$(cc) -o 33b 33b.c

34: 34.c
	$(cc) -o 34 34.c


.PHONY : clean
clean :
	\rm -fr $(objects)

